config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :tweets do
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
  end

  devise_for :users
  
  get 'home/index'
  get 'home/my_profile'
  get 'home/all_tweets', to: 'home#all_tweets', as: 'all_tweets'
  post 'follow/:friend_id', to: 'users#follow', as: 'users_follow'

  #get 'api/news'
  scope '/api' do
    get'/news', to: 'api#news', as: 'api_news'
    get '/:date1/:date2', to: 'api#tweets_by_date', as: 'api_tweets_by_date'
    post '/tweets', to: 'api#create_tweet', as: 'api_create_tweet'
  end

  root to: 'home#index'
end

app/models/tweet.rb
include ActionView::Helpers::UrlHelper

class Tweet < ApplicationRecord
  before_save :add_hashtags

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, :through => :likes, :source => :user

  validates :content, :presence => true

  paginates_per 20

  scope :tweets_for_me, -> (user) { where(user_id: user.arr_friends_id_and_me) }

  def add_hashtags
    new_content = ""
    self.content.split(" ").each do |word|
      if word.start_with?("#")
        word_clean = word.gsub("#", "")
        new_content += '<a href="/?search='+word_clean+'">'+word+'</a>'
        #new_content += link_to(word, Rails.application.routes.url_helpers.root_path+"?search="+word_clean)+ " "
      else
        new_content += word + " "
      end
    end
    self.content = new_content
  end


  def is_liked?(user)
    self.liking_users.include?(user)

  end

  def like(user)
    Like.create(user: user, tweet: self)
  end

  def remove_like(user)
    Like.where(user: user, tweet: self).destroy_all

  end

  def count_rt
    Tweet.where(rt_ref: self.id).count
  end

  def is_retweet?   
    self.rt_ref.present?
  end

  def tweet_ref
    Tweet.find(self.rt_ref )
  end

  ##def self.most_liked 
  #  array = Like.all.pluck(:tweet_id)
  #  hash = array.inject(Hash.new(0)) { |h, x| h[x] += 1; h} 
   # hash.sort_by { |k, v| v }.last(5).to_h
  #end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :set_current_tweet, only: [:likes, :retweet]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  def likes 
    if @tweet.is_liked?(current_user)
      #quitar el like
      @tweet.remove_like(current_user)
    else
      #agregar like
      @tweet.like(current_user)
    end
    redirect_to root_path
  end

  def retweet 
    Tweet.create(content: @tweet.content, user_id: current_user.id, rt_ref: @tweet.id)
    redirect_to root_path
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { redirect_to root_path, alert: "Content is required"}
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def set_current_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="border mt-2 mb-2">
    <h5 class="text-secondary"> <%= image_tag (current_user.avatar), :class => "w-40 circle  ml-3 mt-2 mr-2" %> What's happening?... </h5>
    <br/>
    <%= form.text_area :content, size: '38x3', :class => "text-area ml-2 border-white" %>
  </div>

  
  <%= form.submit "Save", :class => " btn btn-disabled btn-info radio ml-3 rounded-pill" %>


<% end %>

app/views/tweets/_single_tweet.html.erb
<div class="container border p-1 mt-3">
    <div class="row">
        <div class="col-2 ml-2 mt-3">
            <%= image_tag (tweet.user.avatar), :class => "circle" %>
        </div>
        <div class="col-6 p-3">
            <%= link_to "<i class='fa fa-calendar mr-2'></i>".html_safe+time_ago_in_words(tweet.created_at), tweet, class: 'text-dark'%>
            <br>
            <b> <%= tweet.user.username%> dice: </b>
            <%= tweet.content.html_safe %>
            <br/>
            <% if user_signed_in? && current_user != tweet.user %>
                <div>
                    <% if current_user.is_following?(tweet.user_id) %>
                        <%= link_to "<i class='fas fa-user-times text-danger'></i>".html_safe, users_follow_path(tweet.user_id), method: :post %>
                    <% else %>
                        <%= link_to "<i class='fas fa-user-plus'></i>".html_safe, users_follow_path(tweet.user_id), method: :post %>
                    <% end %>
                </div>
            <% end %>
        </div>

        <br/>
        <div class="col-2 p-3">
            <div>
                <% if tweet.is_liked?(current_user) %>
                    <%= link_to "<i class='fas fa-heart text-danger'></i>".html_safe, tweet_likes_path(tweet), method: :post %>
                <% else %>
                    <%= link_to "<i class='far fa-heart text-muted'></i>".html_safe, tweet_likes_path(tweet), method: :post %>
                <% end %>
                <%= tweet.likes.count %> 
            </div>

            <div>
            <% if user_signed_in? %>
                <%= tweet.count_rt %>
                <% if tweet.count_rt > 0 %>
                    <%= link_to "<i class= 'fas fa-retweet text-primary'></i>".html_safe, tweet_retweet_path(tweet), method: :post%>
                <% else %>
                    <%= link_to "<i class= 'fas fa-retweet text-muted'></i>".html_safe, tweet_retweet_path(tweet), method: :post%>

                <% end%>
            <% else %>
                <%= link_to "<i class= 'fas fa-retweet text-muted'></i>".html_safe %>

            <% end %>

                <% if tweet.is_retweet? %>
                    <br/>
                    <%= link_to "Link to original tweet", tweet.tweet_ref, :class => "text-dark" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.content %></td>
        <td><%= tweet.user %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
  <%= render "shared/side_section" %>

  <div class="col-6">
    <div>
      <%= image_tag @tweet.user.avatar, :class => "circle" %>
      <strong><%= @tweet.user.username %>  </strong>
      <br/>
      <%= @tweet.content.html_safe %>
    </div>

    <h5 class="mt-3"> Likes (<%= @tweet.likes.count %>)</h5>

    <% @tweet.liking_users.each do |user| %>
      <%= image_tag( user.avatar , class: "circle") %>

    <% end %>

    <br />

    <%= link_to 'Back', root_path,class: "text-info mt-3"  %>
  </div>
  </div>
</div>