config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :tweets do
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
  end

  devise_for :users
  
  get 'home/index'
  get 'home/my_profile'
  get 'home/all_tweets', to: 'home#all_tweets', as: 'all_tweets'
  post 'follow/:friend_id', to: 'users#follow', as: 'users_follow'

  #get 'api/news'
  scope '/api' do
    get'/news', to: 'api#news', as: 'api_news'
    get '/:date1/:date2', to: 'api#tweets_by_date', as: 'api_tweets_by_date'
    post '/tweets', to: 'api#create_tweet', as: 'api_create_tweet'
  end

  root to: 'home#index'
end

app/views/shared/_footer.html.erb
<footer class="text-center text-light p-3">
    <p>Twitter. Todos los derechos reservados</p>
  </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light p-3 ">
  <div class="container">
    <div class="col-2">
      <a class="navbar-brand" href="<%= root_path %>"><i class="fab fa-twitter fa-2x icono-twitter "></i></a>
    </div>
    
  </div>
</nav>

app/views/shared/_side_section.html.erb
<div class="col-2 links-section pl-0">
    <li class="nav-item">
        <%= link_to "<i class='fas fa-hashtag mr-3'></i>".html_safe+ "Explore", all_tweets_path, class: 'nav-link first-link text-dark w-100 mt-2 rounded-pill'%>
    </li>
    <% if user_signed_in? %>
        <% if current_user.admin %>
            <li class="nav-item">
                <%= link_to "<i class='fa fa-id-card mr-3'></i>".html_safe+"Admin", admin_root_path, class: 'nav-link text-dark mt-2 rounded-pill' %>
            </li>
        <% end%>

        <li class="nav-item">
            <%= link_to "<i class='fas fa-home mr-3'></i>".html_safe+ "Home", root_path, class: 'nav-link second-link text-dark w-100 mt-2 rounded-pill'%>
        </li>

        <li class="nav-item">
            <%= link_to "<i class='fas fa-user mr-3'></i>".html_safe+ "My Profile", home_my_profile_path, class: 'nav-link third-link text-dark w-100 mt-2 rounded-pill'%>
        </li>

        <li class="nav-item">
            <%= link_to "<i class='fas fa-sign-out-alt mr-1'></i>".html_safe+ "Sign out", destroy_user_session_path,class: 'nav-link fourth-link text-dark mt-2 rounded-pill' %>
        </li>

        <!-- Button trigger modal -->
        <button type="button" class="nav-link color-twitter text-center text-light border-light w-100 mt-2 rounded-pill" data-toggle="modal" data-target="#exampleModal">
        Tweet
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                <% if user_signed_in? %>
                <%= render 'tweets/form', tweet: @tweet %>
                <% end %></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            </div>
        </div>
        </div>

        <% else %>
        <li class="nav-item">
            <%= link_to "<i class='fa fa-smile-o mr-2' aria-hidden='true'></i>".html_safe+ "Register", new_user_registration_path, class: 'nav-link second-link text-dark mr-3 rounded-pill' %>
        </li>
        <li class="nav-item">
            <%= link_to "<i class='fa fa-sign-in mr-2' aria-hidden='true'></i>".html_safe+"Log in", new_user_session_path, class: 'nav-link third-link text-dark mr-3 rounded-pill' %>
        </li>
    <% end %>
</div>

app/views/shared/_side_section2.html.erb
<div class="col-2 links-section pl-0">
    <li class="nav-item">
        <%= link_to "<i class='fas fa-hashtag mr-3'></i>".html_safe+ "Explore", all_tweets_path, class: 'nav-link first-link text-dark w-100 mt-2 rounded-pill'%>
    </li>
    <% if user_signed_in? %>
        <% if current_user.admin %>
            <li class="nav-item">
                <%= link_to "<i class='fa fa-id-card mr-3'></i>".html_safe+"Admin", admin_root_path, class: 'nav-link text-dark mt-2 rounded-pill' %>
            </li>
        <% end%>

        <li class="nav-item">
            <%= link_to "<i class='fas fa-home mr-3'></i>".html_safe+ "Home", root_path, class: 'nav-link second-link text-dark w-100 mt-2 rounded-pill'%>
        </li>

        <li class="nav-item">
            <%= link_to "<i class='fas fa-user mr-3'></i>".html_safe+ "My Profile", home_my_profile_path, class: 'nav-link third-link text-dark w-100 mt-2 rounded-pill'%>
        </li>

        <li class="nav-item">
            <%= link_to "<i class='fas fa-sign-out-alt mr-1'></i>".html_safe+ "Sign out", destroy_user_session_path,class: 'nav-link fourth-link text-dark mt-2 rounded-pill' %>
        </li>


        <% else %>
        <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link second-link text-dark mr-3 rounded-pill' %>
        </li>
        <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, class: 'nav-link third-link text-dark mr-3 rounded-pill' %>
        </li>
    <% end %>
</div>